export const elementsCourses = [
    { year: 1, course: 'A' },
    { year: 1, course: 'B' },
    { year: 1, course: 'C' },
    { year: 2, course: 'A' },
    { year: 2, course: 'B' },
    { year: 2, course: 'C' },
    { year: 3, course: 'A' },
    { year: 3, course: 'B' },
    { year: 3, course: 'C' },
    { year: 4, course: 'A' },
    { year: 4, course: 'B' },
    { year: 4, course: 'C' },
    { year: 5, course: 'A' },
    { year: 5, course: 'B' },
    { year: 5, course: 'C' },
    { year: 6, course: 'A' },
    { year: 6, course: 'B' },
    { year: 6, course: 'C' },
    { year: 7, course: 'A' },
    { year: 7, course: 'B' },
    { year: 7, course: 'C'}]